sudo: required

language: ruby

services:
  - docker

branches:
  only:
  - master

before_install:
  - docker build -t sky233/kafka ./kafka
  - docker build -t sky233/kafka-manager ./kafka-manager
  - docker images

script: echo 'test'

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

  # KAFKA
  - docker push sky233/kafka
  # KAFKA_MANAGER
  - docker push sky233/kafka-manager


