version: '3.2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
  kafka:
    build:
      context: kafka/
    image: sky233/kafka:0.11.0.0
    ports:
      - '9092:9092'
    links:
      - zookeeper:zk
    env_file:
        - ./kafka/config/kafka.env
  kafka-manager:
    build:
      context: kafka-manager/
    image: sky233/kafka-manager:latest
    ports:
      - '9000:9000'
    links:
      - zookeeper
      - kafka
    env_file:
        - ./kafka-manager/config/kafka-manager.env
