version: '3.2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
  kafka:
    image: sky233/kafka
    ports:
      - '9092:9092'
    links:
      - zookeeper
    env_file:
        - ./kafka/config/kafka-single.env
  kafka-manager:
    image: sky233/kafka-manager
    ports:
      - '9000:9000'
    links:
      - zookeeper
      - kafka
    env_file:
      - ./kafka-manager/config/kafka-manager.env
